/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID ic312.vit.ac.in)
#  Generated on:      Fri Aug 29 12:22:20 2025
#  Design:            PROCESSOR
#  Command:           saveNetlist PROCESSOR.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jul 29 2025 09:32:24 IST (Jul 29 2025 04:02:24 UTC)
// Verification Directory fv/PROCESSOR 
module PROCESSOR (
	clock, 
	reset, 
	zero);
   input clock;
   input reset;
   output zero;

   // Internal wires
   wire FE_DBTN0_IFU_module_PC_3;
   wire [31:0] IFU_module_PC;
   wire [3:0] alu_control;
   wire [31:0] instruction_code;
   wire IFU_module_n_41;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire datapath_module_reg_file_module_n_48;
   wire n_0;
   wire n_1;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_8;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_17;
   wire n_18;
   wire n_20;
   wire n_21;
   wire n_25;
   wire n_26;
   wire n_39;

   INVX1 FE_DBTC0_IFU_module_PC_3 (.A(IFU_module_PC[3]),
	.Y(FE_DBTN0_IFU_module_PC_3));
   OAI2BB1XL g6704__2398 (.A0N(IFU_module_PC[3]),
	.A1N(n_21),
	.B0(n_20),
	.Y(n_39));
   AOI2BB1XL g6706__5107 (.A0N(IFU_module_PC[3]),
	.A1N(IFU_module_PC[2]),
	.B0(IFU_module_PC[4]),
	.Y(n_21));
   OR2X1 g6707__6260 (.A(IFU_module_PC[4]),
	.B(IFU_module_PC[3]),
	.Y(datapath_module_reg_file_module_n_48));
   NAND2XL g6708__4319 (.A(IFU_module_PC[3]),
	.B(IFU_module_PC[4]),
	.Y(n_26));
   NAND2X1 g6709__8428 (.A(IFU_module_PC[3]),
	.B(IFU_module_PC[2]),
	.Y(n_25));
   NAND2XL g6710__5526 (.A(IFU_module_PC[4]),
	.B(FE_DBTN0_IFU_module_PC_3),
	.Y(n_20));
   OAI21XL g6907__6783 (.A0(n_17),
	.A1(alu_control[2]),
	.B0(n_18),
	.Y(zero));
   NAND4XL g6908__3680 (.A(n_39),
	.B(alu_control[0]),
	.C(alu_control[1]),
	.D(alu_control[2]),
	.Y(n_18));
   MXI2XL g6909__1617 (.S0(alu_control[1]),
	.B(1'b0),
	.A(alu_control[0]),
	.Y(n_17));
   TLATNX1 \control_module_alu_control_reg[2]  (.D(n_11),
	.GN(n_15),
	.Q(UNCONNECTED),
	.QN(alu_control[2]));
   TLATNX1 \control_module_alu_control_reg[0]  (.D(n_8),
	.GN(n_15),
	.Q(alu_control[0]),
	.QN(UNCONNECTED0));
   TLATNX1 \control_module_alu_control_reg[1]  (.D(n_14),
	.GN(n_15),
	.Q(alu_control[1]),
	.QN(UNCONNECTED1));
   NOR2XL g6914__2802 (.A(n_13),
	.B(instruction_code[10]),
	.Y(n_15));
   OAI21XL g6915__1705 (.A0(n_5),
	.A1(IFU_module_PC[4]),
	.B0(n_13),
	.Y(n_14));
   NAND3XL g6916__5122 (.A(datapath_module_reg_file_module_n_48),
	.B(n_12),
	.C(n_25),
	.Y(n_13));
   NAND2XL g6917__8246 (.A(IFU_module_PC[4]),
	.B(IFU_module_n_41),
	.Y(n_12));
   INVX1 g6918 (.A(n_10),
	.Y(n_11));
   AOI21XL g6919__7098 (.A0(n_3),
	.A1(n_26),
	.B0(n_5),
	.Y(n_10));
   OAI2BB1XL g6921__6131 (.A0N(IFU_module_PC[4]),
	.A1N(n_26),
	.B0(n_25),
	.Y(n_8));
   OAI21XL g6922__1881 (.A0(FE_DBTN0_IFU_module_PC_3),
	.A1(IFU_module_PC[2]),
	.B0(n_4),
	.Y(IFU_module_n_41));
   MXI2X1 g6925__5115 (.S0(IFU_module_PC[4]),
	.B(n_3),
	.A(n_25),
	.Y(instruction_code[10]));
   INVX1 g6926 (.A(n_4),
	.Y(n_5));
   NAND2X1 g6927__7482 (.A(FE_DBTN0_IFU_module_PC_3),
	.B(IFU_module_PC[2]),
	.Y(n_4));
   INVX1 g6928 (.A(n_25),
	.Y(n_3));
   DFFRHQX1 \IFU_module_PC_reg[2]  (.D(n_1),
	.CK(clock),
	.RN(n_0),
	.Q(IFU_module_PC[2]));
   DFFRHQX1 \IFU_module_PC_reg[3]  (.D(IFU_module_n_41),
	.CK(clock),
	.RN(n_0),
	.Q(IFU_module_PC[3]));
   DFFRHQX1 \IFU_module_PC_reg[4]  (.D(instruction_code[10]),
	.CK(clock),
	.RN(n_0),
	.Q(IFU_module_PC[4]));
   INVXL g6611 (.A(IFU_module_PC[2]),
	.Y(n_1));
   INVXL g6612 (.A(reset),
	.Y(n_0));
endmodule

